[package]
name = "runen-net-quic"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
quinn = { version = "=0.11.11", default-features = false, features = ["runtime-tokio", "rustls-ring"] }
runen-net = { path = "../runen-net" }
rustls-pki-types = "=1.15.1"

[dev-dependencies]
rcgen = { version = "=0.14.9", default-features = false, features = ["ring"] }
tokio = { version = "=1.53.1", features = ["net", "rt", "time"] }
